FROM node:16
# RUN npm install --global yarn # Already exists
# RUN yarn global add @vue/cli # Not needed here because we're not creating a vue projet (vue create ...) in container.
WORKDIR /app
COPY ./client_vue /app
# RUN yarn install # Not needed because docker at first "executes" Dockerfile (until CMD command) after that mount volumes. https://stackoverflow.com/a/48810282

EXPOSE 8080
CMD yarn serve --host=0.0.0.0 --port=8080